server:
  port: 8084

spring:
  application:
    name: service-product
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

management:
  endpoints:
    web:
      exposure:
        include: health,info
